version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/appvia/artefactor
    steps:
      - checkout
      - run: make test
      - run: make src

  docker_build:
    machine: true
    steps:
     - checkout
     - run: make docker_build

  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/appvia/artefactor
    steps:
      - checkout
      - run: make release
      - run: go get github.com/tcnksm/ghr
      - run: git config --global user.name lewismarshall
      - run: ghr $CIRCLE_TAG ./bin/

  docker_release:
    machine: true
    steps:
     - checkout
     # with credentials stored in the UI
     - run: docker login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
     - run: make docker_build
     - run: make docker_push

workflows:
  version: 2
  run_release:
    jobs:
      - build
      - docker_build
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - docker_release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
